name: sceneops

include:
  - path: ./compose/core.yaml
    project_directory: .
  - path: ./compose/workers.yaml
    project_directory: .
  - path: ./compose/inference.yaml
    project_directory: .
  - path: ./compose/airflow.yaml
    project_directory: .
  - path: ./compose/ros2.yaml
    project_directory: .
  - path: ./compose/tools.yaml
    project_directory: .

networks:
  default:
    name: sceneops-network
