from __future__ import annotations

import time

from pydantic import Field

from sceneops_core.common.schemas import SceneOpsBaseModel

from .enums import EnvelopeEncoding, TelemetryEnvelopeVersion


class TelemetryEnvelope(SceneOpsBaseModel):
    """Transport-level primitive for Phase 6 streaming robot telemetry
    (roadmap Phase 7 in README/ADR-005 terms; Phase 6 in this request's own
    numbering).

    Deliberately NOT a universal SceneOps DataUnit and NOT a domain record
    -- it carries exactly enough metadata to move an opaque binary
    telemetry message through Kafka and reconstruct it exactly on the
    other side. Domain fields (RobotState, Mission, sensor semantics)
    belong inside ``payload``, decoded by something that understands
    ``encoding``/``message_type`` -- never added here.

    Every field below is required with no silent default (``version`` is
    the one exception, defaulting to the only version that exists today)
    so that a malformed/incomplete record fails Pydantic validation
    instead of being silently coerced -- see
    docs/architecture/streaming-transport.md's invalid-message-handling
    section for the full contract.
    """

    version: TelemetryEnvelopeVersion = TelemetryEnvelopeVersion.V1

    robot_id: str = Field(min_length=1)
    robot_run_id: str = Field(min_length=1)

    channel: str = Field(min_length=1)
    message_type: str = Field(min_length=1)

    # Time associated with the robot/sensor observation itself -- never
    # replaced by arrival time. source_timestamp_ns and ingest_timestamp_ns
    # are semantically distinct CLOCKS (observation time vs. transport-
    # boundary-accept time) -- they are two different concepts, not two
    # values guaranteed to differ numerically. A source and its ingest can
    # legitimately be numerically equal (e.g. a synthetic/smoke payload, or
    # a source clock that happens to read the same instant); nothing in
    # this schema enforces or should ever enforce source_timestamp_ns !=
    # ingest_timestamp_ns. See docs/architecture/streaming-transport.md §5.
    source_timestamp_ns: int = Field(gt=0)

    # Time SceneOps accepted the message into the streaming transport
    # boundary. Ownership (frozen, Phase 6.1 follow-up request §4): the
    # SOLE default assignment point is construction of this envelope
    # itself (default_factory below) -- constructing a TelemetryEnvelope
    # IS "accepting the message at the transport boundary" in this
    # architecture. A caller with a more precise boundary-acceptance time
    # (e.g. a future ROS2 bridge/lower transport adapter under an
    # equivalent contract) may always supply its own value explicitly,
    # which simply overrides the default -- there is exactly one place
    # that ever assigns a default value, never a second, competing one
    # inside the producer/consumer/wire layers.
    ingest_timestamp_ns: int = Field(default_factory=lambda: time.time_ns(), gt=0)

    # Monotonic sequence generated by the producer for one logical
    # producer/run stream. Diagnostic only (ordering/duplicate/gap
    # detection) -- never canonical identity.
    sequence_number: int = Field(ge=0)

    encoding: EnvelopeEncoding

    # Binary-first by design: raw bytes, never base64-encoded to fit a
    # JSON envelope. Future high-volume payloads (images, LiDAR, ROS2 CDR)
    # must not require an envelope redesign.
    payload: bytes
