"""add pipeline run orchestration

Revision ID: 559b3b328f38
Revises: 11cc5d349e22
Create Date: 2026-05-23 11:51:31.257281

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '559b3b328f38'
down_revision: str | None = '11cc5d349e22'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_runs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('dataset_id', sa.String(length=128), nullable=False),
    sa.Column('dataset_version', sa.String(length=128), nullable=False),
    sa.Column('model_id', sa.String(length=128), nullable=True),
    sa.Column('model_version', sa.String(length=128), nullable=True),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pipeline_runs_created_at', 'pipeline_runs', ['created_at'], unique=False)
    op.create_index('ix_pipeline_runs_dataset', 'pipeline_runs', ['dataset_id', 'dataset_version'], unique=False)
    op.create_index('ix_pipeline_runs_status', 'pipeline_runs', ['status'], unique=False)
    op.create_index('ix_pipeline_runs_type', 'pipeline_runs', ['type'], unique=False)
    op.create_table('pipeline_step_runs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('pipeline_run_id', sa.String(length=64), nullable=False),
    sa.Column('step_name', sa.String(length=64), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('job_type', sa.String(length=64), nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=True),
    sa.Column('depends_on_step_names', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pipeline_step_runs_job_id', 'pipeline_step_runs', ['job_id'], unique=False)
    op.create_index('ix_pipeline_step_runs_pipeline_run_id', 'pipeline_step_runs', ['pipeline_run_id'], unique=False)
    op.create_index('ix_pipeline_step_runs_pipeline_run_order', 'pipeline_step_runs', ['pipeline_run_id', 'step_order'], unique=False)
    op.create_index('ix_pipeline_step_runs_status', 'pipeline_step_runs', ['status'], unique=False)
    op.add_column('jobs', sa.Column('pipeline_run_id', sa.String(length=64), nullable=True))
    op.add_column('jobs', sa.Column('pipeline_step_run_id', sa.String(length=64), nullable=True))
    op.add_column('jobs', sa.Column('pipeline_step_name', sa.String(length=64), nullable=True))
    op.create_index('ix_jobs_pipeline_run_id', 'jobs', ['pipeline_run_id'], unique=False)
    op.create_index('ix_jobs_pipeline_run_step', 'jobs', ['pipeline_run_id', 'pipeline_step_name'], unique=False)
    op.create_index('ix_jobs_pipeline_step_run_id', 'jobs', ['pipeline_step_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_jobs_pipeline_step_run_id', table_name='jobs')
    op.drop_index('ix_jobs_pipeline_run_step', table_name='jobs')
    op.drop_index('ix_jobs_pipeline_run_id', table_name='jobs')
    op.drop_column('jobs', 'pipeline_step_name')
    op.drop_column('jobs', 'pipeline_step_run_id')
    op.drop_column('jobs', 'pipeline_run_id')
    op.drop_index('ix_pipeline_step_runs_status', table_name='pipeline_step_runs')
    op.drop_index('ix_pipeline_step_runs_pipeline_run_order', table_name='pipeline_step_runs')
    op.drop_index('ix_pipeline_step_runs_pipeline_run_id', table_name='pipeline_step_runs')
    op.drop_index('ix_pipeline_step_runs_job_id', table_name='pipeline_step_runs')
    op.drop_table('pipeline_step_runs')
    op.drop_index('ix_pipeline_runs_type', table_name='pipeline_runs')
    op.drop_index('ix_pipeline_runs_status', table_name='pipeline_runs')
    op.drop_index('ix_pipeline_runs_dataset', table_name='pipeline_runs')
    op.drop_index('ix_pipeline_runs_created_at', table_name='pipeline_runs')
    op.drop_table('pipeline_runs')
    # ### end Alembic commands ###
