"""normalize job manifest type

Revision ID: 5aa23d896f36
Revises: 802d47c872b9
Create Date: 2026-05-24 09:47:26.830253

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5aa23d896f36'
down_revision: str | None = '802d47c872b9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        UPDATE jobs
        SET manifest = jsonb_set(manifest, '{type}', '"ingest_dataset"', false)
        WHERE manifest->>'type' = 'ingest_nuscenes'
        """
    )

    op.execute(
        """
        UPDATE jobs
        SET manifest = jsonb_set(manifest, '{type}', '"predict_detection"', false)
        WHERE manifest->>'type' = 'predict_mock_detection'
        """
    )

    op.execute(
        """
        UPDATE jobs
        SET type = 'ingest_dataset'
        WHERE type = 'ingest_nuscenes'
        """
    )

    op.execute(
        """
        UPDATE jobs
        SET type = 'predict_detection'
        WHERE type = 'predict_mock_detection'
        """
    )

    op.execute(
        """
        UPDATE pipeline_step_runs
        SET job_type = 'ingest_dataset'
        WHERE job_type = 'ingest_nuscenes'
        """
    )

    op.execute(
        """
        UPDATE pipeline_step_runs
        SET job_type = 'predict_detection'
        WHERE job_type = 'predict_mock_detection'
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        UPDATE jobs
        SET manifest = jsonb_set(manifest, '{type}', '"ingest_nuscenes"', false)
        WHERE manifest->>'type' = 'ingest_dataset'
        """
    )

    op.execute(
        """
        UPDATE jobs
        SET manifest = jsonb_set(manifest, '{type}', '"predict_mock_detection"', false)
        WHERE manifest->>'type' = 'predict_detection'
        """
    )

    op.execute(
        """
        UPDATE jobs
        SET type = 'ingest_nuscenes'
        WHERE type = 'ingest_dataset'
        """
    )

    op.execute(
        """
        UPDATE jobs
        SET type = 'predict_mock_detection'
        WHERE type = 'predict_detection'
        """
    )

    op.execute(
        """
        UPDATE pipeline_step_runs
        SET job_type = 'ingest_nuscenes'
        WHERE job_type = 'ingest_dataset'
        """
    )

    op.execute(
        """
        UPDATE pipeline_step_runs
        SET job_type = 'predict_mock_detection'
        WHERE job_type = 'predict_detection'
        """
    )
    # ### end Alembic commands ###
