"""normalize job step statuses

Revision ID: c2b5c2f132c3
Revises: e9c5401c7bdb
Create Date: 2026-05-24 09:56:45.531393

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2b5c2f132c3'
down_revision: str | None = 'e9c5401c7bdb'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        UPDATE jobs
        SET manifest = jsonb_set(
            manifest,
            '{steps}',
            (
                SELECT jsonb_agg(
                    CASE
                        WHEN step ? 'status' THEN
                            jsonb_set(
                                step,
                                '{status}',
                                to_jsonb(lower(step->>'status')),
                                true
                            )
                        ELSE step
                    END
                    ORDER BY ordinality
                )
                FROM jsonb_array_elements(manifest->'steps') WITH ORDINALITY AS item(step, ordinality)
            ),
            true
        )
        WHERE manifest ? 'steps'
          AND jsonb_typeof(manifest->'steps') = 'array'
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        UPDATE jobs
        SET manifest = jsonb_set(
            manifest,
            '{steps}',
            (
                SELECT jsonb_agg(
                    CASE
                        WHEN step ? 'status' THEN
                            jsonb_set(
                                step,
                                '{status}',
                                to_jsonb(upper(step->>'status')),
                                true
                            )
                        ELSE step
                    END
                    ORDER BY ordinality
                )
                FROM jsonb_array_elements(manifest->'steps') WITH ORDINALITY AS item(step, ordinality)
            ),
            true
        )
        WHERE manifest ? 'steps'
          AND jsonb_typeof(manifest->'steps') = 'array'
        """
    )
    # ### end Alembic commands ###
