"""add profile run table

Revision ID: 229554d7dc3a
Revises: 3126fec11e63
Create Date: 2026-05-31 12:08:52.680558

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '229554d7dc3a'
down_revision: str | None = '3126fec11e63'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dataset_profile_runs',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('dataset_id', sa.String(length=128), nullable=False),
    sa.Column('dataset_version', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('dataset_manifest_uri', sa.Text(), nullable=True),
    sa.Column('profile_report_uri', sa.Text(), nullable=True),
    sa.Column('job_id', sa.String(length=128), nullable=True),
    sa.Column('scene_count', sa.Integer(), nullable=True),
    sa.Column('sample_count', sa.Integer(), nullable=True),
    sa.Column('annotation_count', sa.Integer(), nullable=True),
    sa.Column('validated_scene_count', sa.Integer(), nullable=True),
    sa.Column('validated_sample_count', sa.Integer(), nullable=True),
    sa.Column('observed_channel_count', sa.Integer(), nullable=True),
    sa.Column('missing_required_channel_count', sa.Integer(), nullable=True),
    sa.Column('sensor_coverage_ratio', sa.Float(), nullable=True),
    sa.Column('empty_annotation_sample_count', sa.Integer(), nullable=True),
    sa.Column('empty_annotation_sample_ratio', sa.Float(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dataset_profile_runs')
    # ### end Alembic commands ###
