"""create auto label run table

Revision ID: 27ebc9e3649a
Revises: b62e9e41c224
Create Date: 2026-06-02 16:12:26.272444

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '27ebc9e3649a'
down_revision: str | None = 'b62e9e41c224'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auto_label_runs',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('dataset_id', sa.String(length=128), nullable=False),
    sa.Column('dataset_version', sa.String(length=128), nullable=False),
    sa.Column('model_id', sa.String(length=128), nullable=False),
    sa.Column('model_version', sa.String(length=128), nullable=False),
    sa.Column('vlm_backend', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('sample_count', sa.Integer(), nullable=True),
    sa.Column('labeled_sample_count', sa.Integer(), nullable=True),
    sa.Column('auto_label_manifest_uri', sa.Text(), nullable=True),
    sa.Column('samples_root_uri', sa.Text(), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('class_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('pipeline_run_id', sa.String(length=128), nullable=True),
    sa.Column('pipeline_step_run_id', sa.String(length=128), nullable=True),
    sa.Column('job_id', sa.String(length=128), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auto_label_runs_dataset_id'), 'auto_label_runs', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_auto_label_runs_dataset_version'), 'auto_label_runs', ['dataset_version'], unique=False)
    op.create_index(op.f('ix_auto_label_runs_job_id'), 'auto_label_runs', ['job_id'], unique=False)
    op.create_index(op.f('ix_auto_label_runs_model_id'), 'auto_label_runs', ['model_id'], unique=False)
    op.create_index(op.f('ix_auto_label_runs_model_version'), 'auto_label_runs', ['model_version'], unique=False)
    op.create_index(op.f('ix_auto_label_runs_pipeline_run_id'), 'auto_label_runs', ['pipeline_run_id'], unique=False)
    op.create_index(op.f('ix_auto_label_runs_pipeline_step_run_id'), 'auto_label_runs', ['pipeline_step_run_id'], unique=False)
    op.create_index(op.f('ix_auto_label_runs_status'), 'auto_label_runs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auto_label_runs_status'), table_name='auto_label_runs')
    op.drop_index(op.f('ix_auto_label_runs_pipeline_step_run_id'), table_name='auto_label_runs')
    op.drop_index(op.f('ix_auto_label_runs_pipeline_run_id'), table_name='auto_label_runs')
    op.drop_index(op.f('ix_auto_label_runs_model_version'), table_name='auto_label_runs')
    op.drop_index(op.f('ix_auto_label_runs_model_id'), table_name='auto_label_runs')
    op.drop_index(op.f('ix_auto_label_runs_job_id'), table_name='auto_label_runs')
    op.drop_index(op.f('ix_auto_label_runs_dataset_version'), table_name='auto_label_runs')
    op.drop_index(op.f('ix_auto_label_runs_dataset_id'), table_name='auto_label_runs')
    op.drop_table('auto_label_runs')
    # ### end Alembic commands ###
