"""raw data uri to source uri

Revision ID: dbff9f6d9dc8
Revises: 4c8035709a02
Create Date: 2026-05-30 11:06:30.683240

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbff9f6d9dc8'
down_revision: str | None = '4c8035709a02'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset_versions', sa.Column('source_uri', sa.Text(), nullable=True))
    op.drop_column('dataset_versions', 'raw_data_uri')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset_versions', sa.Column('raw_data_uri', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('dataset_versions', 'source_uri')
    # ### end Alembic commands ###
