"""add job orchestration fields

Revision ID: ff43540871bf
Revises: 41a032689622
Create Date: 2026-05-23 08:03:37.011706

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff43540871bf'
down_revision: str | None = '41a032689622'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('retry_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('jobs', sa.Column('max_retries', sa.Integer(), server_default='0', nullable=False))
    op.add_column('jobs', sa.Column('worker_id', sa.String(length=128), nullable=True))
    op.add_column('jobs', sa.Column('queued_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('jobs', sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('jobs', sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index('ix_jobs_queued_at', 'jobs', ['queued_at'], unique=False)
    op.create_index('ix_jobs_worker_id', 'jobs', ['worker_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_jobs_worker_id', table_name='jobs')
    op.drop_index('ix_jobs_queued_at', table_name='jobs')
    op.drop_column('jobs', 'heartbeat_at')
    op.drop_column('jobs', 'locked_at')
    op.drop_column('jobs', 'queued_at')
    op.drop_column('jobs', 'worker_id')
    op.drop_column('jobs', 'max_retries')
    op.drop_column('jobs', 'retry_count')
    # ### end Alembic commands ###
