from __future__ import annotations

import time
from enum import StrEnum

from pydantic import Field

from sceneops_core.common.schemas import SceneOpsBaseModel


class TelemetryEnvelopeVersion(StrEnum):
    """Streaming-envelope schema version -- deliberately independent of
    DatasetVersion, source-format version, and MCAP schema version. Only
    ``V1`` exists today; an envelope carrying any other value fails
    Pydantic validation, which is what gives the consumer's "unknown
    envelope version" rejection for free."""

    V1 = "v1"


class EnvelopeEncoding(StrEnum):
    """How ``TelemetryEnvelope.payload`` bytes are encoded. Transport-level
    only -- the envelope never decodes the payload itself, this just tells
    a downstream consumer which decoder to reach for."""

    ROS2_CDR = "ros2-cdr"
    JSON = "json"
    RAW = "raw"


class TelemetryEnvelope(SceneOpsBaseModel):
    """Transport-level primitive for streaming robot telemetry (the
    robot-runtime-communication vs. data-platform-event-stream boundary
    decided in ADR-005).

    Deliberately NOT a universal SceneOps DataUnit and NOT a domain record
    -- it carries exactly enough metadata to move an opaque binary
    telemetry message through Kafka and reconstruct it exactly on the
    other side. Domain fields (RobotState, Mission, sensor semantics)
    belong inside ``payload``, decoded by something that understands
    ``encoding``/``message_type`` -- never added here.

    Every field below is required with no silent default (``version`` is
    the one exception, defaulting to the only version that exists today)
    so that a malformed/incomplete record fails Pydantic validation
    instead of being silently coerced -- see
    docs/architecture/streaming-transport.md's invalid-message-handling
    section for the full contract.
    """

    version: TelemetryEnvelopeVersion = TelemetryEnvelopeVersion.V1

    robot_id: str = Field(min_length=1)
    robot_run_id: str = Field(min_length=1)

    channel: str = Field(min_length=1)
    message_type: str = Field(min_length=1)

    # Time associated with the robot/sensor observation itself -- never
    # replaced by arrival time. source_timestamp_ns and ingest_timestamp_ns
    # are semantically distinct CLOCKS (observation time vs. transport-
    # boundary-accept time) -- they are two different concepts, not two
    # values guaranteed to differ numerically. A source and its ingest can
    # legitimately be numerically equal (e.g. a synthetic/smoke payload, or
    # a source clock that happens to read the same instant); nothing in
    # this schema enforces or should ever enforce source_timestamp_ns !=
    # ingest_timestamp_ns. See docs/architecture/streaming-transport.md §4.
    #
    # 0 is a legal value and means "the source message carries a zero
    # timestamp" (ROS 2's unstamped Header, typical of /tf_static). It is
    # the source's own value passed through verbatim, never a substitute
    # for a missing one; which channels may carry it is a per-channel
    # decision of the producer (sceneops_streaming.channels).
    source_timestamp_ns: int = Field(ge=0)

    # Time SceneOps accepted the message into the streaming transport
    # boundary. Ownership: the SOLE default assignment point is
    # construction of this envelope itself (default_factory below) --
    # constructing a TelemetryEnvelope IS "accepting the message at the
    # transport boundary" in this architecture. A caller with a more
    # precise boundary-acceptance time (e.g. the ROS2 bridge, or another
    # transport adapter under an equivalent contract) may always supply
    # its own value explicitly, which simply overrides the default --
    # there is exactly one place that ever assigns a default value, never
    # a second, competing one inside the producer/consumer/wire layers.
    ingest_timestamp_ns: int = Field(default_factory=lambda: time.time_ns(), gt=0)

    # Monotonic sequence generated by the producer for one logical
    # producer/run stream. Diagnostic only (ordering/duplicate/gap
    # detection) -- never canonical identity.
    sequence_number: int = Field(ge=0)

    encoding: EnvelopeEncoding

    # Binary-first by design: raw bytes, never base64-encoded to fit a
    # JSON envelope. Future high-volume payloads (images, LiDAR, ROS2 CDR)
    # must not require an envelope redesign.
    payload: bytes
