"""create job events table

Revision ID: 11cc5d349e22
Revises: ff43540871bf
Create Date: 2026-05-23 09:18:30.933802

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '11cc5d349e22'
down_revision: str | None = 'ff43540871bf'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_events',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_job_events_created_at', 'job_events', ['created_at'], unique=False)
    op.create_index('ix_job_events_event_type', 'job_events', ['event_type'], unique=False)
    op.create_index('ix_job_events_job_id', 'job_events', ['job_id'], unique=False)
    op.create_index('ix_job_events_job_id_created_at', 'job_events', ['job_id', 'created_at'], unique=False)
    # op.alter_column('jobs', 'error',
    #            existing_type=sa.TEXT(),
    #            type_=postgresql.JSONB(astext_type=sa.Text()),
    #            existing_nullable=True)
    op.execute(
        """
        ALTER TABLE jobs
        ALTER COLUMN error TYPE JSONB
        USING
            CASE
                WHEN error IS NULL THEN NULL
                WHEN trim(error) = '' THEN NULL
                ELSE jsonb_build_object('message', error)
            END
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('jobs', 'error',
    #            existing_type=postgresql.JSONB(astext_type=sa.Text()),
    #            type_=sa.TEXT(),
    #            existing_nullable=True)
    op.execute(
        """
        ALTER TABLE jobs
        ALTER COLUMN error TYPE TEXT
        USING
            CASE
                WHEN error IS NULL THEN NULL
                ELSE error::text
            END
        """
    )
    op.drop_index('ix_job_events_job_id_created_at', table_name='job_events')
    op.drop_index('ix_job_events_job_id', table_name='job_events')
    op.drop_index('ix_job_events_event_type', table_name='job_events')
    op.drop_index('ix_job_events_created_at', table_name='job_events')
    op.drop_table('job_events')
    # ### end Alembic commands ###
