"""create models and runs

Revision ID: 4c8035709a02
Revises: 2f009033ffe7
Create Date: 2026-05-27 16:18:55.563036

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4c8035709a02'
down_revision: str | None = '2f009033ffe7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evaluation_runs',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('inference_run_id', sa.String(length=128), nullable=False),
    sa.Column('dataset_id', sa.String(length=128), nullable=False),
    sa.Column('dataset_version', sa.String(length=128), nullable=False),
    sa.Column('model_id', sa.String(length=128), nullable=False),
    sa.Column('model_version', sa.String(length=128), nullable=False),
    sa.Column('evaluator_id', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('sample_count', sa.Integer(), nullable=True),
    sa.Column('evaluation_manifest_uri', sa.Text(), nullable=True),
    sa.Column('samples_root_uri', sa.Text(), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('class_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('pipeline_run_id', sa.String(length=128), nullable=True),
    sa.Column('pipeline_step_run_id', sa.String(length=128), nullable=True),
    sa.Column('job_id', sa.String(length=128), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluation_runs_dataset_id'), 'evaluation_runs', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_evaluation_runs_dataset_version'), 'evaluation_runs', ['dataset_version'], unique=False)
    op.create_index(op.f('ix_evaluation_runs_inference_run_id'), 'evaluation_runs', ['inference_run_id'], unique=False)
    op.create_index(op.f('ix_evaluation_runs_job_id'), 'evaluation_runs', ['job_id'], unique=False)
    op.create_index(op.f('ix_evaluation_runs_model_id'), 'evaluation_runs', ['model_id'], unique=False)
    op.create_index(op.f('ix_evaluation_runs_model_version'), 'evaluation_runs', ['model_version'], unique=False)
    op.create_index(op.f('ix_evaluation_runs_pipeline_run_id'), 'evaluation_runs', ['pipeline_run_id'], unique=False)
    op.create_index(op.f('ix_evaluation_runs_pipeline_step_run_id'), 'evaluation_runs', ['pipeline_step_run_id'], unique=False)
    op.create_index(op.f('ix_evaluation_runs_status'), 'evaluation_runs', ['status'], unique=False)
    op.create_table('inference_runs',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('dataset_id', sa.String(length=128), nullable=False),
    sa.Column('dataset_version', sa.String(length=128), nullable=False),
    sa.Column('model_id', sa.String(length=128), nullable=False),
    sa.Column('model_version', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('sample_count', sa.Integer(), nullable=True),
    sa.Column('prediction_count', sa.Integer(), nullable=True),
    sa.Column('run_manifest_uri', sa.Text(), nullable=True),
    sa.Column('predictions_root_uri', sa.Text(), nullable=True),
    sa.Column('pipeline_run_id', sa.String(length=128), nullable=True),
    sa.Column('pipeline_step_run_id', sa.String(length=128), nullable=True),
    sa.Column('job_id', sa.String(length=128), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inference_runs_dataset_id'), 'inference_runs', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_inference_runs_dataset_version'), 'inference_runs', ['dataset_version'], unique=False)
    op.create_index(op.f('ix_inference_runs_job_id'), 'inference_runs', ['job_id'], unique=False)
    op.create_index(op.f('ix_inference_runs_model_id'), 'inference_runs', ['model_id'], unique=False)
    op.create_index(op.f('ix_inference_runs_model_version'), 'inference_runs', ['model_version'], unique=False)
    op.create_index(op.f('ix_inference_runs_pipeline_run_id'), 'inference_runs', ['pipeline_run_id'], unique=False)
    op.create_index(op.f('ix_inference_runs_pipeline_step_run_id'), 'inference_runs', ['pipeline_step_run_id'], unique=False)
    op.create_index(op.f('ix_inference_runs_status'), 'inference_runs', ['status'], unique=False)
    op.create_table('models',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_versions',
    sa.Column('id', sa.String(length=256), nullable=False),
    sa.Column('model_id', sa.String(length=128), nullable=False),
    sa.Column('version', sa.String(length=128), nullable=False),
    sa.Column('backend', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('model_uri', sa.Text(), nullable=True),
    sa.Column('endpoint_url', sa.Text(), nullable=True),
    sa.Column('runtime', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_id', 'version', name='uq_model_versions_model_id_version')
    )
    op.create_index(op.f('ix_model_versions_model_id'), 'model_versions', ['model_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_model_versions_model_id'), table_name='model_versions')
    op.drop_table('model_versions')
    op.drop_table('models')
    op.drop_index(op.f('ix_inference_runs_status'), table_name='inference_runs')
    op.drop_index(op.f('ix_inference_runs_pipeline_step_run_id'), table_name='inference_runs')
    op.drop_index(op.f('ix_inference_runs_pipeline_run_id'), table_name='inference_runs')
    op.drop_index(op.f('ix_inference_runs_model_version'), table_name='inference_runs')
    op.drop_index(op.f('ix_inference_runs_model_id'), table_name='inference_runs')
    op.drop_index(op.f('ix_inference_runs_job_id'), table_name='inference_runs')
    op.drop_index(op.f('ix_inference_runs_dataset_version'), table_name='inference_runs')
    op.drop_index(op.f('ix_inference_runs_dataset_id'), table_name='inference_runs')
    op.drop_table('inference_runs')
    op.drop_index(op.f('ix_evaluation_runs_status'), table_name='evaluation_runs')
    op.drop_index(op.f('ix_evaluation_runs_pipeline_step_run_id'), table_name='evaluation_runs')
    op.drop_index(op.f('ix_evaluation_runs_pipeline_run_id'), table_name='evaluation_runs')
    op.drop_index(op.f('ix_evaluation_runs_model_version'), table_name='evaluation_runs')
    op.drop_index(op.f('ix_evaluation_runs_model_id'), table_name='evaluation_runs')
    op.drop_index(op.f('ix_evaluation_runs_job_id'), table_name='evaluation_runs')
    op.drop_index(op.f('ix_evaluation_runs_inference_run_id'), table_name='evaluation_runs')
    op.drop_index(op.f('ix_evaluation_runs_dataset_version'), table_name='evaluation_runs')
    op.drop_index(op.f('ix_evaluation_runs_dataset_id'), table_name='evaluation_runs')
    op.drop_table('evaluation_runs')
    # ### end Alembic commands ###
