"""rename to artifacts

Revision ID: 9962d62d9c25
Revises: 0001
Create Date: 2026-06-04 17:20:05.660578

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9962d62d9c25'
down_revision: str | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artifacts',
    sa.Column('artifact_id', sa.String(length=128), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('uri', sa.Text(), nullable=False),
    sa.Column('backend', sa.String(length=64), nullable=True),
    sa.Column('owner_type', sa.String(length=64), nullable=True),
    sa.Column('owner_id', sa.String(length=128), nullable=True),
    sa.Column('dataset_id', sa.String(length=128), nullable=True),
    sa.Column('dataset_version', sa.String(length=128), nullable=True),
    sa.Column('scene_id', sa.String(length=128), nullable=True),
    sa.Column('scenario_set_id', sa.String(length=128), nullable=True),
    sa.Column('run_id', sa.String(length=128), nullable=True),
    sa.Column('job_id', sa.String(length=128), nullable=True),
    sa.Column('pipeline_run_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('media_type', sa.String(length=128), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('checksum', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('artifact_id')
    )
    op.create_index('ix_artifacts_dataset', 'artifacts', ['dataset_id', 'dataset_version'], unique=False)
    op.create_index('ix_artifacts_job_id', 'artifacts', ['job_id'], unique=False)
    op.create_index('ix_artifacts_kind', 'artifacts', ['kind'], unique=False)
    op.create_index('ix_artifacts_owner', 'artifacts', ['owner_type', 'owner_id'], unique=False)
    op.create_index('ix_artifacts_pipeline_run_id', 'artifacts', ['pipeline_run_id'], unique=False)
    op.create_index('ix_artifacts_run_id', 'artifacts', ['run_id'], unique=False)
    op.create_index('ix_artifacts_scene_id', 'artifacts', ['scene_id'], unique=False)
    op.drop_index(op.f('ix_artifact_refs_dataset'), table_name='artifacts_refs')
    op.drop_index(op.f('ix_artifact_refs_job_id'), table_name='artifacts_refs')
    op.drop_index(op.f('ix_artifact_refs_kind'), table_name='artifacts_refs')
    op.drop_index(op.f('ix_artifact_refs_owner'), table_name='artifacts_refs')
    op.drop_index(op.f('ix_artifact_refs_pipeline_run_id'), table_name='artifacts_refs')
    op.drop_index(op.f('ix_artifact_refs_run_id'), table_name='artifacts_refs')
    op.drop_index(op.f('ix_artifact_refs_scene_id'), table_name='artifacts_refs')
    op.drop_table('artifacts_refs')
    op.add_column('job_events', sa.Column('pipeline_step_id', sa.String(length=128), nullable=True))
    op.drop_column('job_events', 'pipeline_step_name')
    op.add_column('jobs', sa.Column('pipeline_step_id', sa.String(length=128), nullable=True))
    op.drop_column('jobs', 'pipeline_step_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('pipeline_step_name', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_column('jobs', 'pipeline_step_id')
    op.add_column('job_events', sa.Column('pipeline_step_name', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_column('job_events', 'pipeline_step_id')
    op.create_table('artifacts_refs',
    sa.Column('artifact_id', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('kind', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('uri', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('backend', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('owner_type', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('owner_id', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('dataset_id', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('dataset_version', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('scene_id', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('scenario_set_id', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('run_id', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('job_id', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('pipeline_run_id', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('media_type', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('size_bytes', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('checksum', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('artifact_id', name=op.f('artifacts_refs_pkey'))
    )
    op.create_index(op.f('ix_artifact_refs_scene_id'), 'artifacts_refs', ['scene_id'], unique=False)
    op.create_index(op.f('ix_artifact_refs_run_id'), 'artifacts_refs', ['run_id'], unique=False)
    op.create_index(op.f('ix_artifact_refs_pipeline_run_id'), 'artifacts_refs', ['pipeline_run_id'], unique=False)
    op.create_index(op.f('ix_artifact_refs_owner'), 'artifacts_refs', ['owner_type', 'owner_id'], unique=False)
    op.create_index(op.f('ix_artifact_refs_kind'), 'artifacts_refs', ['kind'], unique=False)
    op.create_index(op.f('ix_artifact_refs_job_id'), 'artifacts_refs', ['job_id'], unique=False)
    op.create_index(op.f('ix_artifact_refs_dataset'), 'artifacts_refs', ['dataset_id', 'dataset_version'], unique=False)
    op.drop_index('ix_artifacts_scene_id', table_name='artifacts')
    op.drop_index('ix_artifacts_run_id', table_name='artifacts')
    op.drop_index('ix_artifacts_pipeline_run_id', table_name='artifacts')
    op.drop_index('ix_artifacts_owner', table_name='artifacts')
    op.drop_index('ix_artifacts_kind', table_name='artifacts')
    op.drop_index('ix_artifacts_job_id', table_name='artifacts')
    op.drop_index('ix_artifacts_dataset', table_name='artifacts')
    op.drop_table('artifacts')
    # ### end Alembic commands ###
