"""refactor schema

Revision ID: b62e9e41c224
Revises: 505c62154828
Create Date: 2026-05-31 15:59:49.684423

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b62e9e41c224'
down_revision: str | None = '505c62154828'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset_profile_runs', sa.Column('scope', sa.String(length=32), nullable=True))
    op.add_column('dataset_profile_runs', sa.Column('max_samples', sa.Integer(), nullable=True))
    op.add_column('dataset_profile_runs', sa.Column('profiled_scene_count', sa.Integer(), nullable=True))
    op.add_column('dataset_profile_runs', sa.Column('profiled_sample_count', sa.Integer(), nullable=True))
    op.add_column('dataset_profile_runs', sa.Column('observed_channels', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('dataset_profile_runs', 'status',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.create_index(op.f('ix_dataset_profile_runs_dataset_id'), 'dataset_profile_runs', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_dataset_profile_runs_dataset_version'), 'dataset_profile_runs', ['dataset_version'], unique=False)
    op.create_index(op.f('ix_dataset_profile_runs_status'), 'dataset_profile_runs', ['status'], unique=False)
    op.drop_column('dataset_profile_runs', 'validated_sample_count')
    op.drop_column('dataset_profile_runs', 'validated_scene_count')
    op.add_column('dataset_validation_runs', sa.Column('decision_reason', sa.Text(), nullable=True))
    op.add_column('dataset_versions', sa.Column('raw_data_uri', sa.Text(), nullable=True))
    op.add_column('dataset_versions', sa.Column('latest_validation_run_id', sa.String(length=128), nullable=True))
    op.add_column('dataset_versions', sa.Column('validation_status', sa.String(length=32), nullable=True))
    op.add_column('dataset_versions', sa.Column('should_block_pipeline', sa.Boolean(), nullable=True))
    op.add_column('dataset_versions', sa.Column('validation_report_uri', sa.Text(), nullable=True))
    op.add_column('dataset_versions', sa.Column('validation_issue_count', sa.Integer(), nullable=True))
    op.add_column('dataset_versions', sa.Column('validation_error_count', sa.Integer(), nullable=True))
    op.add_column('dataset_versions', sa.Column('validation_warning_count', sa.Integer(), nullable=True))
    op.add_column('dataset_versions', sa.Column('missing_scene_count', sa.Integer(), nullable=True))
    op.add_column('dataset_versions', sa.Column('missing_sample_count', sa.Integer(), nullable=True))
    op.add_column('dataset_versions', sa.Column('missing_channel_count', sa.Integer(), nullable=True))
    op.add_column('dataset_versions', sa.Column('missing_artifact_count', sa.Integer(), nullable=True))
    op.add_column('dataset_versions', sa.Column('latest_profile_run_id', sa.String(length=128), nullable=True))
    op.add_column('dataset_versions', sa.Column('profile_report_uri', sa.Text(), nullable=True))
    op.add_column('dataset_versions', sa.Column('profiled_scene_count', sa.Integer(), nullable=True))
    op.add_column('dataset_versions', sa.Column('profiled_sample_count', sa.Integer(), nullable=True))
    op.add_column('dataset_versions', sa.Column('observed_channel_count', sa.Integer(), nullable=True))
    op.add_column('dataset_versions', sa.Column('observed_channels', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('dataset_versions', sa.Column('missing_required_channel_count', sa.Integer(), nullable=True))
    op.add_column('dataset_versions', sa.Column('sensor_coverage_ratio', sa.Float(), nullable=True))
    op.add_column('dataset_versions', sa.Column('empty_annotation_sample_count', sa.Integer(), nullable=True))
    op.add_column('dataset_versions', sa.Column('empty_annotation_sample_ratio', sa.Float(), nullable=True))
    op.create_index(op.f('ix_dataset_versions_latest_profile_run_id'), 'dataset_versions', ['latest_profile_run_id'], unique=False)
    op.create_index(op.f('ix_dataset_versions_latest_validation_run_id'), 'dataset_versions', ['latest_validation_run_id'], unique=False)
    op.create_index(op.f('ix_dataset_versions_status'), 'dataset_versions', ['status'], unique=False)
    op.create_index(op.f('ix_dataset_versions_validation_status'), 'dataset_versions', ['validation_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dataset_versions_validation_status'), table_name='dataset_versions')
    op.drop_index(op.f('ix_dataset_versions_status'), table_name='dataset_versions')
    op.drop_index(op.f('ix_dataset_versions_latest_validation_run_id'), table_name='dataset_versions')
    op.drop_index(op.f('ix_dataset_versions_latest_profile_run_id'), table_name='dataset_versions')
    op.drop_column('dataset_versions', 'empty_annotation_sample_ratio')
    op.drop_column('dataset_versions', 'empty_annotation_sample_count')
    op.drop_column('dataset_versions', 'sensor_coverage_ratio')
    op.drop_column('dataset_versions', 'missing_required_channel_count')
    op.drop_column('dataset_versions', 'observed_channels')
    op.drop_column('dataset_versions', 'observed_channel_count')
    op.drop_column('dataset_versions', 'profiled_sample_count')
    op.drop_column('dataset_versions', 'profiled_scene_count')
    op.drop_column('dataset_versions', 'profile_report_uri')
    op.drop_column('dataset_versions', 'latest_profile_run_id')
    op.drop_column('dataset_versions', 'missing_artifact_count')
    op.drop_column('dataset_versions', 'missing_channel_count')
    op.drop_column('dataset_versions', 'missing_sample_count')
    op.drop_column('dataset_versions', 'missing_scene_count')
    op.drop_column('dataset_versions', 'validation_warning_count')
    op.drop_column('dataset_versions', 'validation_error_count')
    op.drop_column('dataset_versions', 'validation_issue_count')
    op.drop_column('dataset_versions', 'validation_report_uri')
    op.drop_column('dataset_versions', 'should_block_pipeline')
    op.drop_column('dataset_versions', 'validation_status')
    op.drop_column('dataset_versions', 'latest_validation_run_id')
    op.drop_column('dataset_versions', 'raw_data_uri')
    op.drop_column('dataset_validation_runs', 'decision_reason')
    op.add_column('dataset_profile_runs', sa.Column('validated_scene_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('dataset_profile_runs', sa.Column('validated_sample_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_dataset_profile_runs_status'), table_name='dataset_profile_runs')
    op.drop_index(op.f('ix_dataset_profile_runs_dataset_version'), table_name='dataset_profile_runs')
    op.drop_index(op.f('ix_dataset_profile_runs_dataset_id'), table_name='dataset_profile_runs')
    op.alter_column('dataset_profile_runs', 'status',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
    op.drop_column('dataset_profile_runs', 'observed_channels')
    op.drop_column('dataset_profile_runs', 'profiled_sample_count')
    op.drop_column('dataset_profile_runs', 'profiled_scene_count')
    op.drop_column('dataset_profile_runs', 'max_samples')
    op.drop_column('dataset_profile_runs', 'scope')
    # ### end Alembic commands ###
