from __future__ import annotations

from typing import Any, Protocol


class ArtifactStore(Protocol):
    async def read_json(self, uri: str) -> Any: ...

    async def write_json(self, uri: str, data: Any) -> None: ...

    async def exists(self, uri: str) -> bool: ...

    async def list_json(self, uri: str) -> list[str]: ...

    async def delete_prefix(self, uri: str) -> None: ...

    def join_uri(self, *parts: str) -> str: ...
