INGEST_NUSCENES_STEPS = [
    "LOAD_NUSCENES_METADATA",
    "BUILD_DATASET_MANIFEST",
    "BUILD_SCENE_MANIFESTS",
    "BUILD_SAMPLE_MANIFESTS",
    "SAVE_MANIFESTS",
]

PREDICT_MOCK_DETECTION_STEPS = [
    "LOAD_DATASET_MANIFEST",
    "LOAD_SAMPLE_MANIFESTS",
    "GENERATE_MOCK_PREDICTIONS",
    "SAVE_INFERENCE_RUN",
    "SAVE_PREDICTION_ARTIFACTS",
]

EVALUATE_DETECTION_STEPS = [
    "LOAD_INFERENCE_RUN",
    "LOAD_GT_ANNOTATIONS",
    "LOAD_PREDICTIONS",
    "MATCH_BOXES",
    "COMPUTE_METRICS",
    "SAVE_EVALUATION_RUN",
]
