CAMERA_CHANNELS = {
    "CAM_FRONT",
    "CAM_FRONT_LEFT",
    "CAM_FRONT_RIGHT",
    "CAM_BACK",
    "CAM_BACK_LEFT",
    "CAM_BACK_RIGHT",
}

LIDAR_CHANNELS = {
    "LIDAR_TOP",
}

RADAR_CHANNELS = {
    "RADAR_FRONT",
    "RADAR_FRONT_LEFT",
    "RADAR_FRONT_RIGHT",
    "RADAR_BACK_LEFT",
    "RADAR_BACK_RIGHT",
}

DEFAULT_TARGET_CHANNELS = {
    "CAM_FRONT",
    "LIDAR_TOP",
}
